config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :categories
  resources :items
  resources :outfit_items
  resources :outfits
  resources :users

  get '/welcome', to: 'application#welcome' 
  get '/new_account', to: 'application#new_account'
  post '/create_account', to: 'application#create_account'
  get '/home', to: 'application#home'
  get '/analytics', to: 'application#analytics'
  get '/login', to: 'auth#new'
  post '/login', to: 'auth#create'
  delete '/login', to: 'auth#destroy'
  
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items 

    @@all = Category.all 

    def self.total_items
        @@all.count 
    end

    def self.most_items
        max_num = @@all.map{|c| c.items.count}.max
        @@all.find{|c|c.items.count == max_num}.name 
    end

    def self.fewest_items
        min_num = @@all.map{|c| c.items.count}.min 
        @@all.find{|c| c.items.count == min_num}.name 
    end

    def total_items
        self.items.count 
    end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category, required: false 
  belongs_to :style, required: false 
  has_many :outfit_items
  has_many :outfits, through: :outfit_items 
  
  def self.most_popular
    #most popular item for users 
    user_outfits = User.all.map{|u| u.outfits}.flatten
    user_items = user_outfits.map{|o| o.items}.flatten
    user_items.max_by{|i| user_items.count(i)}.name 
  end

  def self.least_popular
    #least popular item for users
    user_outfits = User.all.map{|u| u.outfits}.flatten
    user_items = user_outfits.map{|o| o.items}.flatten
    user_items.min_by{|i| user_items.count(i)}.name 
  end

  def self.most_sought_after_brand
    user_outfits = User.all.map{|u| u.outfits}.flatten
    user_items = user_outfits.map{|o| o.items}.flatten
    user_brands = user_items.map{|i| i.brand}.flatten
    user_brands.max_by{|b| user_brands.count(b)}
  end

end

app/models/outfit.rb
class Outfit < ApplicationRecord
  belongs_to :user, required: false 
  has_many :outfit_items, dependent: :destroy
  has_many :items, through: :outfit_items
  validates :name, presence: true

  def self.most_items
    #outfit with the most items
    max_num = self.all.map{|o| o.items.count}.max
    self.all.find{|o| o.items.count == max_num}.name 
  end

end

app/models/outfit_item.rb
class OutfitItem < ApplicationRecord
  belongs_to :outfit, required: false
  belongs_to :item, required: false
end

app/models/style.rb
class Style < ApplicationRecord
    has_many :items

    @@all = Style.all 

    def self.total_items
        @@all.count 
    end

    def self.most_items
        max_num = @@all.map{|s| s.items.count}.max
        @@all.find{|s|s.items.count == max_num}.name 
    end

    def self.fewest_items
        min_num = @@all.map{|s| s.items.count}.min 
        @@all.find{|s| s.items.count == min_num}.name 
    end

    def total_items
        self.items.count 
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :outfits, dependent: :destroy
    has_many :outfit_items, through: :outfits
    has_secure_password
    
    def to_s
        self.first_name + ' ' + self.last_name 
    end

    def formalize
        "Mr. #{self.to_s}"
    end

    def self.most_outfits
        max_num = self.all.map{|u| u.outfits.count}.max
        self.all.find{|u| u.outfits.count == max_num}.formalize
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user 

    def current_user
        user_id = session[:user_id]
        user_id && User.find(user_id)
    end

    def authorize!
        unless current_user
            flash[:notice] = "You must be logged in to do that."
            redirect_to login_path
        end 
    end

    def logged_in?
        if current_user
            flash[:notice] = "You are already logged in."
            @user = User.find(session[:user_id])
            redirect_to user_path(@user)
        end 
    end

    def welcome
    end

    def new_account
        @user = User.new 
    end

    def create_account
        @user.update(user_params)
    end

    def home
        current_user
    end

    def analytics
    end

    private

    def user_params
        params.require(:user).permit(:name, :age, :bio, :username, :password)
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :logged_in?, only: :new 
  
  def new
    end

    def create
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
          # cookies[user_id]
          session[:user_id] = @user.id
          redirect_to home_path
        else
          flash[:notice] = "Incorrect username or password."
          render :new
        end
    end

    def destroy
        session.delete(:user_id)
        flash[:notice] = "You are logged out."
        redirect_to welcome_path
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    helper_method :uniq_users
    
    def index
        @items = Item.all 
    end

    def show
        @item = Item.find(params[:id])
    end

    def uniq_users
        array = [] 
        @item = Item.find(params[:id])
        @item.outfits.each do |o|
          array << o.user.to_s
        end
        array = array.uniq
      end

end

app/controllers/outfit_items_controller.rb
class OutfitItemsController < ApplicationController
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
    before_action :authorize!, only:[:new, :edit, :update, :destroy]

    def index
    @outfits = Outfit.all
end
def show
    @outfit = Outfit.find(params[:id])
end
def new
    @outfit = Outfit.new
end

def create
    @outfit = Outfit.new(params.require(:outfit).permit(:name))
    @outfit.user_id = session[:user_id]
    if @outfit.save
        redirect_to outfit_path(@outfit)
    else
        render new_outfit_path
    end
end

def edit
    @outfit = Outfit.find(params[:id])
    @items = Item.all
end

def update
    @outfit = Outfit.find(params[:id])
    @item = Item.find(params[:outfit][:id])
    @outfit.items << @item
    redirect_to outfit_path(@outfit)
end

def destroy
    @outfit = Outfit.find(params[:id])
    @outfit.destroy
    redirect_to outfits_path
end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :logged_in?, only: :new
    def show
    end
    
    def new
        @user = User.new 
    end

    def create
        @user = User.create(user_params)
        session[:user_id] = @user.id
        flash[:notice] = "Welcome #{@user.first_name}! Your account was created successfully!"
        redirect_to user_path(@user)
    end

    def edit
        
    end

    def update
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    def destroy
        # byebug
        session.delete(:user_id)
        @user.destroy
        redirect_to welcome_path 
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :bio, :age, :username, :password)
    end

    def set_user
        @user = User.find(session[:user_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/outfit_items_helper.rb
module OutfitItemsHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/analytics.html.erb
<div class = "analytics_page">
    <div class = "analytics_header">
        <h2>Site Analytics</h2>
    </div>
    <div class = "analytics_info">
        <h3>Categories</h3>
        <h5>Total Categories: <%=Category.count%></h5>
        <h5>Category with most items: <%=Category.most_items%></h5>
        <h5>Category with fewest items: <%=Category.fewest_items%></h5>
        <br>
        <h3>Styles</h3>
        <h5>Total Styles: <%=Style.count%></h5>
        <h5>Style with most items: <%=Style.most_items%></h5>
        <h5>Style with fewest items: <%=Style.fewest_items%></h5>
        <br>
        <h3>Items</h3>
        <h5>Total Items: <%=Item.all.count%></h5>
        <h5>Most popular item: <%=Item.most_popular%></h5>
        <h5>Least popular item: <%=Item.least_popular%></h5>
        <h5>Most sought after brand: <%=Item.most_sought_after_brand%></h5>
        <br>
        <h3>Users</h3>
        <h5>User with most outfits: <%=User.most_outfits%></h5>
    </div>
</div>

app/views/application/home.html.erb
<div class="logged_in">
    <h2>Welcome back, <%=current_user.first_name%>!</h2>

    <p>What would you like to do?</p>

    <%=link_to 'Browse Outfits', outfits_path%> | <%=link_to 'Create Outfit', new_outfit_path%> | <%=link_to 'Browse Items', items_path%>
</div>

app/views/application/new_account.html.erb
<h3>Welcome to StyleX!  We're glad you're here!</h3>

<p><b>To get started, please provide the following information</b></p>

<%=form_for @user do |f|%>
    First Name: <%=f.text_field :first_name%><br>
    Last Name: <%=f.text_field :last_name%><br>
    Bio: <%=f.text_area :bio%><br>
    Age: <%=f.number_field :age%><br>
    Username: <%=f.text_field :username%><br>
    Password: <%=f.password_field :password%><br>
    <%=f.submit 'Create Account'%>
<%end%>

app/views/application/welcome.html.erb
<div class = "welcome">
    <p></p>
</div>

<div class="welcome_content">
    <div class='welcome_title'>
        <h1>Hello, welcome to StyleX.</h1>
        <h2>Inspiration for your daily outfits, personal style, and life outlook.</h2>
    </div>


    <div class='nonheading'>
        <div class='login_ask'>
            <h3>Please login or create an account.</h3>
        </div>
        <div class='buttons'>
            <div class='login_button'><%=button_to 'Login', '/login', {:class => "buttonTo", method: :get} %></div>
            <div class='login_button'><%=button_to 'New Account', new_user_path, {:class => "buttonTo", method: :get}%></div>
        </div>
    </div>
    <footer id = "footer">
        <p>Made with &hearts; by John Odom and Curtis Arnold.  |  <%=link_to 'Site Analytics', analytics_path%></p>
    </footer>
</div>

app/views/items/index.html.erb
<div class = "items">
    <p></p>
</div>

<div class="items_text">

    <div class="category_browse_title">
        <h2>Browse by Category</h2>
    </div>

    <div class="category_browse">
        
        <div class="category_box">
            <h3> Shoes </h3>
            <ul>
            <% @items.each do |item|%>
                <%if item.category.name == "shoes"%>
                    <li> <%= link_to item.name, item_path(item) %> </li>
                <%end%>
            <%end%>
            </ul>
        </div>

        <div class="category_box">
            <h3> Shirts </h3>
            <ul>
            <% @items.each do |item|%>
                <%if item.category.name == "tops"%>
                    <li> <%= link_to item.name, item_path(item) %> </li>
                <%end%>
            <%end%>
            </ul>
        </div>

        <div class="category_box">
            <h3> Pants </h3>
            <ul>
            <% @items.each do |item|%>
                <%if item.category.name == "bottoms"%>
                    <li> <%= link_to item.name, item_path(item) %> </li>
                <%end%>
            <%end%>
            </ul>
        </div>

        <div class="category_box">
            <h3> Accessories </h3>
            <ul>
            <% @items.each do |item|%>
                <%if item.category.name == "accessories"%>
                    <li> <%= link_to item.name, item_path(item) %> </li>
                <%end%>
            <%end%>
            </ul>
        </div>

        <div class="category_box">
            <h3> Suits </h3>
            <ul>
            <% @items.each do |item|%>
                <%if item.category.name == "suits"%>
                    <li> <%= link_to item.name, item_path(item) %> </li>
                <%end%>
            <%end%>
            </ul>
        </div>

    </div>

    <div class="style_browse_title">
        <h2>Browse by Style</h2>
    </div>

    <div class = "style_browse">

        <div class="style_box">
            <h3> Business </h3>
            <ul>
            <% @items.each do |item|%>
                <%if item.style.name == "business"%>
                    <li> <%= link_to item.name, item_path(item) %> </li>
                <%end%>
            <%end%>
            </ul>
        </div>

        <div class = "style_box">
            <h3> Casual </h3>
            <ul>
            <% @items.each do |item|%>
                <%if item.style.name == "casual"%>
                    <li> <%= link_to item.name, item_path(item) %> </li>
                <%end%>
            <%end%>
            </ul>
        </div>

        <div class="style_box">
            <h3> Athletic </h3>
            <ul>
            <% @items.each do |item|%>
                <%if item.style.name == "athletic"%>
                    <li> <%= link_to item.name, item_path(item) %> </li>
                <%end%>
            <%end%>
            </ul>
        </div>

        <div class="style_box">
            <h3> Formal </h3>
            <ul>
            <% @items.each do |item|%>
                <%if item.style.name == "formal"%>
                    <li> <%= link_to item.name, item_path(item) %> </li>
                <%end%>
            <%end%>
            </ul>
        </div>

    </div >

</div>

app/views/items/show.html.erb
<div class = "items_show_page">
    <div class = "item_name_to_category">
        <h2><%=@item.name%></h2>
        <h3><%=@item.brand%></h3>

        <%= image_tag(@item.img_url, :alt => "landing pic") %>



        <p>Item Style: <%=@item.style.name%></p>
        <p>Item Category: <%=@item.category.name%></p>
    </div>
        
    <div class = "users_with_items_in_outfits">
        <p>Users with this item in their outfits:</p>

        <ul>
        <%uniq_users.each do |user|%>
            <li> <%=user%> </li>
        <%end%>
        </ul>

        <br>

        <%=link_to 'All Items', items_path%>
    <div>
</div>

app/views/outfits/edit.html.erb
<div class = "edit_outfit_page">
    
    <div class = "edit_outfit_heading">
        <h2>Edit Your Outfit</h2>
    </div>

    <div class = "edit_page_details">
        <div class = "outfit_details">
            <div class = "outfit_name">
                <h3> Outfit Name:   <%=@outfit.name.capitalize%> </h3>
            </div>

            <div class = "outfit_items">
                <ul>
                <%@outfit.items.each do |item|%>
                    <li><%=item.name%></li>
                <%end%>
                </ul>
            </div>

            <div class = "add_item_to_outfit_bar">
                <h2>Add Item to Outfit</h2>
                <%=form_for @outfit do |f|%>
                <%=f.collection_select(:id, @items, :id, :name)%>
                <%=f.submit%>
                <%end%>
            </div>
            <br>
            <%=link_to "View your Outfit", outfit_path(@outfit)%>
        </div>

        


        <div class = "all_items_shown">
            <div class = "items_header">
                <h3> Items </h3>
            </div>
            <div class = "all_items_on_edit_outfit">
                <% @items.each do |item| %>
                    <div class = "item_block">
                        <div class = "each_item_name">
                            <h5><%=item.name%><h5>
                        </div>
                        <div class = "each_item_img">
                            <%=image_tag(item.img_url, :alt => "Item Picture")%>
                        </div>
                    </div>
                <%end%>
            </div>
        </div>
    </div>
</div>

app/views/outfits/index.html.erb
<div class = "outfits">
    <p></p>
</div>

<div class="outfit_text">
    <h3>All Outfits</h3>

    <ul>
    <%@outfits.each do |outfit|%>
        <li><%=link_to outfit.name, outfit_path(outfit)%> - <%=outfit.user.to_s%></li><br>
    <%end%>
    <ul>

    <%=link_to "Create an Outfit", new_outfit_path%>
</div>

app/views/outfits/new.html.erb
<%if @outfit.errors.present?%>

    <p>  -  Outfit must have a name! </p>
<%end%>

<div class="create_outfit">
    <p></p>
</div>

<div class="create_outfit_text">
    <h2>Nice.  You're on your way.</h2>
    <h2>Please provide a name for your new outfit to continue.</h2>

    <%=form_for @outfit do |f|%>
    <%=f.text_field :name%>
    <%=f.submit%>
    <%end%>
</div>

app/views/outfits/show.html.erb
<div class="outfit_show">
    <p></p>
</div>

<%# <div class = "outfit_show_page"> %>

    <div class = "outfit_show_header">
        <h1><%=@outfit.name%></h1>

        
        <%if session[:user_id] == @outfit.user_id%>
            <%=link_to "Add Items to Outfit", edit_outfit_path%>
            <br>
            <%=button_to "Delete Your Outfit", outfit_path(@outfit), method: :delete%><br>
           
        <%end%>
    </div>


    <div class="outfit_show_text">


        

        <div class='all_items'>
            <%@outfit.items.each do |i|%>
                <div class="item_div">
                    <div class="image">
                        <%= image_tag(i.img_url, :alt => "Item Picture") %>
                    </div>
                    <div class="info">
                        <ul>
                            <li>Name: <%=i.name%></li>
                            <li>Brand: <%=i.brand%></li>
                            <li>Category: <%=i.category.name%></li>
                            <li>Style: <%=i.style.name%></li><br>
                            <%form_tag outfit_path method: %>
                        </ul>
                    </div>
                </div>
            <%end%>
        </div>
         
    </div>
    <br>
    <%=link_to "View All Outfits", outfits_path%>
<%# </div> %>

app/views/users/_form.html.erb
<%=form_for @user do |f|%>
    <%=f.label 'First Name: '%>
    <%=f.text_field :first_name%><br><br>
    <%=f.label 'Last Name: '%>
    <%=f.text_field :last_name%><br><br>
    <%=f.label 'Age: '%>
    <%=f.number_field :age%><br><br>
    <%=f.label 'Bio: '%>
    <%=f.text_area :bio%><br><br>
    <%=f.label 'Username: '%>
    <%=f.text_field :username%><br><br>
    <%=f.label 'Password: '%>
    <%=f.password_field :password%><br><br>
    <%=f.submit%>
<%end%>
<br><br>

app/views/users/edit.html.erb
<h3>Edit Profile</h3>

<h3><%=@user.to_s%></h3>
<p><%=@user.bio%></p>
<p><%=@user.age%></p>

<h4>Current Outfits: </h4>
<ul>
    <%@user.outfits.each do |o|%>
        <li><%=link_to o.name, outfit_path(o)%></li>
    <%end%>
</ul>

<p><b>Please fill in the following information: </b></p>

<%=render 'form'%>

<%=link_to "Home", home_path%>

<%=link_to 'Delete Account', user_path(@user), method: :delete%> 

app/views/users/new.html.erb
<div class="new_account">
    <p></p>
</div>

<div class="new_account_text">
    <h3>Welcome to StyleX!  We're glad you're here!</h3>

    <p><b>To create your account, please provide the following information: </b></p>

    <%=render 'form'%>

    <%=link_to "Home", welcome_path%>
</div>

app/views/users/show.html.erb
    <% if flash[:notice] %>
    <% end %>

<div class ="user_text">    
    <h3><%=@user.to_s%></h3>
    <p><%=@user.bio%></p>
    <p><%=@user.age%></p>

    <h4>Current Outfits: </h4>
    <ul>
        <%@user.outfits.each do |o|%>
            <li><%=link_to o.name, outfit_path(o)%></li>
        <%end%>
    </ul>

    <%=link_to 'Edit Profile', edit_user_path(@user)%> | 
    <%=link_to 'Delete Account', user_path(@user), method: :delete%> |
    <%=link_to 'Home', home_path%> <br>

    <%=link_to 'Browse All Outfits', outfits_path%> |
    <%=link_to 'Create an Outfit', new_outfit_path%>
</div>